name: Flutter CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    # 1.
    - name: Install dependencies
      run: flutter pub get
    
    # 2. 
    - name: Building APK
      run: flutter build apk

    # 3.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Releases
        path: | 
          build/app/outputs/flutter-apk/app-release.apk

    # 4.
    - name: Extract version from pubspec.yaml
      id: extract_version
      run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

    # 5.
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

